logging:
  level:
    root: info
    com.psc.sample: debug
server:
  port: 8080
spring:
  profiles:
    active: window
  batch:
    job:
      names: ${job.name:NONE}
  application:
    name: chunkSizeAndParallel
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true # 로그 확인
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    username:
    password: